#ifndef DUNE16_REGISTER_H
#define DUNE16_REGISTER_H

enum {
    REGISTER_A,
    REGISTER_B,
    REGISTER_C,
    REGISTER_D,
    REGISTER_PC,
    REGISTER_LR,
    REGISTER_COUNT,
};

#endif // DUNE16_REGISTER_H
